export const mockPlayList = [
    {
        id: 1,
        title: "WISH (Korean Ver.)",
        artist: "NCT WISH",
        album: "WISH",
        duration: "03:06",
        thumbnail: "https://i.namu.wiki/i/wVpYu6B-eOOOf_NxRpN6tO1cnwuGPBP2NgFwtAygQKYxUUN9ll-Y8JHgpUpLrXpWK5-sjpAjLS2mZhBXvQwDVn5wpCF5AI6CZB80J_0p6R7NSws97_Z43tbcGqCzAvvvYP3vVNkz4VZ9lWIurg1Rrg.webp",
      }, 
    {
        id: 2,
        title: "WISH (Japanese Ver.)",
        artist: "NCT WISH",
        album: "WISH",
        duration: "03:06",
        thumbnail: "https://i.namu.wiki/i/wVpYu6B-eOOOf_NxRpN6tO1cnwuGPBP2NgFwtAygQKYxUUN9ll-Y8JHgpUpLrXpWK5-sjpAjLS2mZhBXvQwDVn5wpCF5AI6CZB80J_0p6R7NSws97_Z43tbcGqCzAvvvYP3vVNkz4VZ9lWIurg1Rrg.webp",
      }, 
    {
        id: 3,
        title: "Sail Away (Korean Ver.)",
        artist: "NCT WISH",
        album: "WISH",
        duration: "03:26",
        thumbnail: "https://i.namu.wiki/i/wVpYu6B-eOOOf_NxRpN6tO1cnwuGPBP2NgFwtAygQKYxUUN9ll-Y8JHgpUpLrXpWK5-sjpAjLS2mZhBXvQwDVn5wpCF5AI6CZB80J_0p6R7NSws97_Z43tbcGqCzAvvvYP3vVNkz4VZ9lWIurg1Rrg.webp",
      },    
    {
        id: 4,
        title: "Sail Away (Japanese Ver.)",
        artist: "NCT WISH",
        album: "WISH",
        duration: "03:26",
        thumbnail: "https://i.namu.wiki/i/wVpYu6B-eOOOf_NxRpN6tO1cnwuGPBP2NgFwtAygQKYxUUN9ll-Y8JHgpUpLrXpWK5-sjpAjLS2mZhBXvQwDVn5wpCF5AI6CZB80J_0p6R7NSws97_Z43tbcGqCzAvvvYP3vVNkz4VZ9lWIurg1Rrg.webp",
      }, 
    {
        id: 5,
        title: "Songbird",
        artist: "NCT WISH",
        album: "Songbird",
        duration: "03:02",
        thumbnail: "https://i.namu.wiki/i/yCNgi_EW-InWZT35Sm0_y1G53htqGARu_pxkiEIcWQ4QjTGy7Gn3nUHhXEH66oIoMkTWZyg1KafqtTmFEsZQkUbKGvI2T2FBwPMZ812TwPZKM507rH9BO6CNDQKZSVNtO3DniAlmTlgCm3od9pVB9g.webp",
      }, 
    {
        id: 6,
        title: "Tears Are Falling",
        artist: "NCT WISH",
        album: "Songbird",
        duration: "03:05",
        thumbnail: "https://i.namu.wiki/i/yCNgi_EW-InWZT35Sm0_y1G53htqGARu_pxkiEIcWQ4QjTGy7Gn3nUHhXEH66oIoMkTWZyg1KafqtTmFEsZQkUbKGvI2T2FBwPMZ812TwPZKM507rH9BO6CNDQKZSVNtO3DniAlmTlgCm3od9pVB9g.webp",
      }, 
      {
        id: 7,
        title: "Songbird (Japanese Ver.)",
        artist: "NCT WISH",
        album: "Songbird",
        duration: "03:02",
        thumbnail: "https://i.namu.wiki/i/yCNgi_EW-InWZT35Sm0_y1G53htqGARu_pxkiEIcWQ4QjTGy7Gn3nUHhXEH66oIoMkTWZyg1KafqtTmFEsZQkUbKGvI2T2FBwPMZ812TwPZKM507rH9BO6CNDQKZSVNtO3DniAlmTlgCm3od9pVB9g.webp",
      }, 
     
];
